### ISSUE TITLE
Does not compile with ESP8266 version 2.6.3

### ISSUE THREAD

**Issue by woeperbe** [yasheena/telnetspy#11]
Compiling error when i try to compile with esp8266 2.6.3 platform

**Comment by rvt** [comment]
Perhaps it helps if you let everybody know what the actual compile error is?

**Comment by woeperbe** [comment]
i changed a few lines in the code and it works now
i will email you what i did

Greetings,
Marc Buffet


On 2 Jun 2020, at 10:17, R. van Twisk <notifications@github.com> wrote:

﻿

Perhaps it helps if you let everybody know what the actual compile error is?

**Comment by woeperbe** [comment]
I works ... sorry my mistake
