### ISSUE TITLE
Verbose output from serial is not transferred via Telnet

### ISSUE THREAD

**Issue by mrdc** [yasheena/telnetspy#15]
Hello,

Unfortunately, verbose output from serial is not transferred via Telnet only Print, Println etc.

**Comment by yasheena** [comment]
Hi,

I just want to release a new version of TelnetSpy and I want to consider as much as possible. I know, you write this issue two years ago, but can you give me some more information, please? Have you examples where data is not also transferred via Telnet?

**Comment by yasheena** [comment]
I think you had this problem with ESP32. Now fixed in version 1.4.
