### ISSUE TITLE
TelnetSpy.cpp: In member function 'void 

### ISSUE THREAD

**Issue by riskiadi** [yasheena/telnetspy#18]
C:\Users\ucupu\Documents\Arduino\libraries\TelnetSpy\TelnetSpy.cpp: In member function 'void TelnetSpy::setDebugOutput(bool)':
C:\Users\ucupu\Documents\Arduino\libraries\TelnetSpy\TelnetSpy.cpp:406:42: error: invalid conversion from 'void*' to 'fp_putc_t {aka void (*)(char)}' [-fpermissive]
   os_install_putc1((void*) TelnetSpy_putc);  // Set system printing (os_printf) to TelnetSpy
                                          ^
In file included from C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/os_type.h:28:0,
                 from C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/user_interface.h:28,
                 from C:\Users\ucupu\Documents\Arduino\libraries\TelnetSpy\TelnetSpy.cpp:12:
C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/ets_sys.h:219:6: error:   initializing argument 1 of 'void ets_install_putc1(fp_putc_t)' [-fpermissive]
 void ets_install_putc1(fp_putc_t routine);
      ^
C:\Users\ucupu\Documents\Arduino\libraries\TelnetSpy\TelnetSpy.cpp:415:50: error: invalid conversion from 'void*' to 'fp_putc_t {aka void (*)(char)}' [-fpermissive]
    os_install_putc1((void*) TelnetSpy_ignore_putc); // Ignore system printing
                                                  ^
In file included from C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/os_type.h:28:0,
                 from C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/user_interface.h:28,
                 from C:\Users\ucupu\Documents\Arduino\libraries\TelnetSpy\TelnetSpy.cpp:12:
C:\Users\ucupu\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/include/ets_sys.h:219:6: error:   initializing argument 1 of 'void ets_install_putc1(fp_putc_t)' [-fpermissive]
 void ets_install_putc1(fp_putc_t routine);
      ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by yasheena** [comment]
Fixed in version 1.2
