### ISSUE TITLE
newlines not rendered on Windows telnet

### ISSUE THREAD

**Issue by proddy** [yasheena/telnetspy#3]
Thanks for the great library. I'm using it in one of my projects to replace some home grown telnet logging libraries. I noticed when using Telnet on Windows the newlines are not left-justified. I think this is because you need a '\r' after a '\n'. For example using your stock example code in a Serial window it shows correctly as:

```
Connecting to WiFi . Connected!
Ready
IP address: 10.10.10.28

Type 'C' for WiFi connect.
Type 'D' for WiFi disconnect.
Type 'R' for WiFi reconnect.
All other chars will be echoed. Play around...
```
 
but in the telnet window:

```
                                Connecting to WiFi . Connected!
Ready
IP address: 10.10.10.28

Type 'C' for WiFi connect.
                          Type 'D' for WiFi disconnect.
                                                       Type 'R' for WiFi reconnect.
All other chars will be echoed. Play around...

Telnet connection established.

```

Works fine using telnet from Linux, like an ubuntu shell in Windows10 though.

**Comment by yasheena** [comment]
There is a solution without adding code:
In the putty configuration (Category:) click on "terminal" and check the line "Implicit CR in every LF".

**Comment by proddy** [comment]
yes, that'll work. Also using the windows telnet.exe with
https://support.microsoft.com/en-nz/help/322846/telnet-client-does-not-send-crlf-when-expected
