### ISSUE TITLE
disconnect telnet client feature?

### ISSUE THREAD

**Issue by proddy** [yasheena/telnetspy#4]
One idea to add is a function to close a telnet client session. For example in an active Telnet session, I would capture a ctrl-D (from a `SerialAndTelnet.read()`) which would exit the Telnet session, but keep the serial and everything else active. The only way I think you could do this now is by calling end() which kills both the server and client? 

so like

```
void TelnetSpy::disconnectClient() {
    if (client.connected()) {
        client.flush();
        client.stop();
    }
    if (connected && (callbackDisconnect != NULL)) {
        callbackDisconnect();
    }
    connected = false;
}

**Comment by arezi** [comment]
it would be great! :)

**Comment by mkh595** [comment]
> The only way I think you could do this now is by calling end() which kills both the server and client?

You can call ```SerialAndTelnet.setPort()``` and this will restart only telnet session.

My application already use HTTP client so telnet session is never ended when telnet client is closed.

**Comment by yasheena** [comment]
Thank you for your hint. Added for version 1.2.
