### ISSUE TITLE
Does not work in AP only mode (ESP32)

### ISSUE THREAD

**Issue by rljonesau** [yasheena/telnetspy#9]
I was never able to establish a connection when using AP only mode on an ESP32 (never tried an 8266).

I have changed the code in handle() to do this about line 548 (commented out below) and I can now use a telnet client when using the AP connection:

	```
if (!listening) {

    wifi_mode_t currentMode = WiFi.getMode();
    bool isAPEnabled = ((currentMode & WIFI_MODE_AP) != 0);
    bool isSTAconnected = WiFi.status() == WL_CONNECTED;

//		if (WiFi.status() != WL_CONNECTED) {
    if (!isSTAconnected && !isAPEnabled) 
        return;
    }
```

**Comment by yasheena** [comment]
Fixed with version 1.2
